### PR TITLE
feat(backend): Add support for backend mutation in https://github.com…

### PR DESCRIPTION
**Pull request by cellis**
…/nodkz/relay-northwind-app/pull

This change simply exposes the preexisting mutation in graphql-compose-mongoose

Addresses https://github.com/nodkz/relay-northwind-app/issues/1 . Doesn't use the heroku db as that
would be insecure. @nodkz's call here. Perhaps next step is auth ;)

### CODE REVIEW

**Comment by cellis** [comment]
@nodkz see latest here: https://github.com/nodkz/relay-northwind-app/pull/3

**Comment by nodkz** [comment]
Let's fix insecure mutation:
```js
GQC.rootMutation().addFields({
  createProduct: ProductTC.get('$createOne'),
  removeProductById: ProductTC.get('$removeById'),
});
```
Let forbid mutation on Heroku, but allows on localhost (another [example](https://twitter.com/nodkz/status/817234620014034945)):
```js
GQC.rootMutation().addFields({
  ...allowOnlyForLocalhost({
    createProduct: ProductTC.get('$createOne'),
    removeProductById: ProductTC.get('$removeById'),
  }),
});

function allowOnlyForLocalhost(resolvers) {
  Object.keys(resolvers).forEach((k) => {
    resolvers[k] = resolvers[k].wrapResolve(next => (rp) => {
      if (rp.context.ip === '127.0.0.1' || rp.context.ip === '0:0:0:0:0:0:0:1' || __DEV__ === true) {
        return next(rp);
      }
      throw new Error('For security reason mutation are disabled on Heroku, but will work on your localhost. Please clone https://github.com/nodkz/graphql-compose-examples repo and start server locally.');
    });
  });
  return resolvers;
}
```

So with code above, mutations may not work (i do not remember does `req` provided to `context` by default or not). So let prepare `context` explicitly. For this needs to edit [graphqlHTTP](https://github.com/nodkz/graphql-compose-examples/blob/master/index.js):
```js
  server.use(example.uri, graphqlHTTP(req => ({
    schema: example.schema,
    graphiql: true,
    formatError: (error) => ({
      message: error.message,
      stack: error.stack.split('\n'),
    }),
    context: {
       ip: req.ip || (req.connection || {}).remoteAddress,
       // isAdmin: somehow_check_is_admin_from_req_object(req),
       // req: req, // may add request
       // dataLoaders: [],  // may provide other helpers to context 
    },
  }))); 
```

Also we can setup global `__DEV__` variable. It can be done with webpack via [webpack.DefinePlugin](https://webpack.github.io/docs/list-of-plugins.html#defineplugin) in file. But in this repo we do not use Webpack, so let omit it.

**Comment by nodkz** [comment]
Additional 5 cents about context (Auth and other staff).

GraphQL does not contain any built-in auth mechanism. You should do it yourself before passing request to graphqlHTTP. In my app I'm using JWT (but in last time it got too many negative feedback) and maybe I'll migrate to something other. Anyway, principle providing auth data to GraphQL will be the same - via patching `req` and providing it to `context`.

```js
server.use('/graphql', myJWT.validateRequest, graphqlHTTP(req => ({ ... })));
```
You may replace `myJWT.validateRequest` on any express middleware which extend `req` with additional data. Eg.
```js
myJWT.validateRequest = (req, res, next) => {
  const jwtData = parseFromHeaders(req) || {};
  let userPromise;
  req.userId = jwtData.uid;
  req.getUserPromise = () => {
     if (!userPromise) {
       userPromise = req.userId  ? UserModel.findById(req.userId) : Promise.resolve(null);
     }
     return userPromise;
  }
  next();
};
```
And then passing all required data to graphql context: 
```js
  context: {
    userId: req.userId,
    getUserPromise: req.getUserPromise,
  }
```

I'm found very useful to have helper method `getUserPromise` to obtain `User` fetched only once from DB and only if it needed in my resolvers (otherwise it will not be called from db). So in resolvers I can do such things:
```js
GQC.rootQuery().addFields({
  userRawData: {
     type: 'Json',
     resolve: (source, args, context) => {
        return context.getUserPromise();
     }
  },
  somethingComputable: {
     type: 'Int',
     resolve: (source, args, context) => {
        return context.getUserPromise().then((user) => {
           if (user) {
              return user.a + user.b;
           }
           return null;
        });
     }    
  },
  freeArticles: ArticleTC.get('$findMany').wrapResolve(next => rp => {
     return rp.context.getUserPromise().then((user) => {
        if (user && user.karma > 10) {
           return next(rp);
        }
        return null; 
        // or 
        // throw new Error('You karma should be greater than 10, for viewing articles');
     }); 
  }); 
})
```
So in this case if we request all fields from `rootQuery` we only once fetch User from DB. And when it will be resolved from DB, all other 3 chains will be proceeded and return some data.

**Comment by nodkz** [comment]
@cellis please protect mutation as described in https://github.com/nodkz/graphql-compose-examples/pull/2#issuecomment-276308242

**Comment by cellis** [comment]
@nodkz will resolve all of these this weekend ( and tomorrow ). Sorry for the delay.

**Comment by nodkz** [comment]
@cellis I just worried that we still not came to complex mutations, which were as your main request. But if you have time and this not block you at work, I'm in calmness 😉.

**Comment by cellis** [comment]
@nodkz. I think I now actually understand how to do complex mutations, but still want to complete this exercise to help teach the community. I want to use this technology to build amazing apps -- much easier if there's a solid community backing it. For a solid community, we need easy to follow tutorials, hence why I'm continuing this.

**Comment by cellis** [comment]
@nodkz ready to close this out and move on to next chapter of graphql-compose. I think I'm ready to work on that knex-resolver and understand things a lot more now.

**Comment by nodkz** [comment]
Sorry for delay, too much work right now. Try to review this and others PRs and answer to your questions tomorrow.

**Comment by nodkz** [comment]
Made some changes https://github.com/nodkz/graphql-compose-examples/commit/3fd6b4616908b276846529b75d3a56af3e4969f3

Beautify error. Small renaming.

**Comment by nodkz** [comment]
@cellis do you want to setup `dotenv` module here? (had problem with 4000 port 🙁 on heroku instead of my 3000)

**Comment by cellis** [comment]
@nodkz will do. Also I have a few questions for you in the other relay-northwind-app PR.

**Pull request merged**
